services:
  hive:
    image: killbasa/hive
    build:
      dockerfile: apps/api/Dockerfile
      context: .
    env_file:
      - apps/api/.env
    environment:
      REDIS_HOST: valkey
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
    volumes:
      - ./data:/var/lib/hive
    ports:
      - 127.0.0.1:3001:3001
    depends_on:
      - valkey

  web:
    image: killbasa/hive-web
    build:
      dockerfile: apps/web/Dockerfile
      context: .
    environment:
      VITE_API_URL: http://localhost:3001
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - hive

  valkey:
    image: valkey/valkey:8.0.1-alpine3.20
    restart: unless-stopped
    command: ["valkey-server", "--requirepass password"]
