services:
  hive:
    image: killbasa/hive
    container_name: hive
    build:
      dockerfile: apps/api/Dockerfile
      context: .
    env_file:
      - apps/api/.env
    environment:
      PORT: 3001
      REDIS_HOST: hive-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
    volumes:
      - ./data:/var/lib/hive
    ports:
      - 127.0.0.1:3001:3001

  web:
    image: killbasa/hive-web
    container_name: hive-web
    build:
      dockerfile: apps/web/Dockerfile
      context: .
    environment:
      VITE_API_URL: http://localhost:3001
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - hive
