version: "3.9"

services:
  hive:
    image: killbasa/hive
    container_name: hive
    build:
      dockerfile: apps/api/Dockerfile
      context: .
    env_file:
      - apps/api/.env
    environment:
      NODE_ENV: production
      PORT: 3001
      REDIS_HOST: hive-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
    volumes:
      - ./apps/api:/data
    ports:
      - 127.0.0.1:3001:3001

  web:
    image: killbasa/hive-web
    container_name: hive-web
    build:
      dockerfile: apps/web/Dockerfile
      context: .
      args:
        VITE_API_URL: localhost:3001
    ports:
      - 127.0.0.1:3000:80
    depends_on:
      - hive
