build:
	go build -o ./bin/hive main.go

debug *args: build
	go run main.go {{args}}

install: build
	go install

gen:
	rm -rf ./client
	openapi-generator generate -i ../apps/api/openapi.json \
		-g go \
		-o ./client \
		--additional-properties=packageName=client,isGoSubmodule \
		--global-property=models,apis,apiDocs=false,modelDocs=false,apiTests=false,modelTests=false,supportingFiles=response.go:utils.go:configuration.go:client.go

