services:
  redis:
    image: redis:7.4.3-alpine3.21
    restart: unless-stopped
    command: ["redis-server", "--requirepass password"]
    ports:
      - 127.0.0.1:6379:6379

  nginx:
    image: nginx:1.26.3-alpine3.20 # Needs to match version in Dockerfile
    restart: unless-stopped
    network_mode: host
    environment:
      CONFIG: "--with-http_mp4_module"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - ./data/media:/var/lib/hive/media:ro
