services:
  valkey:
    image: valkey/valkey:8.0.2-alpine3.21
    restart: unless-stopped
    command: ["valkey-server", "--requirepass password"]
    ports:
      - 127.0.0.1:6379:6379

  nginx:
    image: nginx:1.26.2-alpine3.20 # Needs to match Dockerfile version
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - ./data/media:/var/lib/hive/media:ro
