name: CI

on:
  pull_request:
    paths-ignore:
      - "**/*.md"

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4.1.7

      - name: Set up NodeJS
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 22.12.0
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Run build
        run: pnpm build

      - name: Run linting and formatting
        run: pnpm check

      - name: Run tests
        run: pnpm test
