name: CI

on:
  pull_request:
    paths-ignore:
      - "**/*.md"

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda

      - name: Set up NodeJS
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Run build
        run: pnpm build

      - name: Install built dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Run linting and formatting
        run: pnpm check

      - name: Run tests
        run: pnpm test
