name: CI

on:
  pull_request:
    paths-ignore:
      - "**/*.md"

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up NodeJS
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version-file: package.json
          cache: yarn

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Run build
        run: yarn build

      - name: Run linting and formatting
        run: yarn check

      - name: Run tests
        run: yarn test
