name: CI

on:
  pull_request:
    paths-ignore:
      - "**/*.md"

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4.1.1

      - name: Set up NodeJS
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Run typecheck
        run: pnpm check

      - name: Run lint
        run: |
          pnpm format
          pnpm lint

      - name: Run build
        run: pnpm build
