name: Publish

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  publish-nightly:
    name: Build and publish (nightly)
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4.1.4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3.3.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (api)
        uses: docker/build-push-action@v5.3.0
        with:
          push: true
          file: ./apps/api/Dockerfile
          context: .
          tags: |
            ghcr.io/killbasa/hive:latest
            ghcr.io/killbasa/hive:nightly

      - name: Build and push Docker image (web)
        uses: docker/build-push-action@v5.3.0
        with:
          push: true
          file: ./apps/api/Dockerfile
          context: .
          tags: |
            ghcr.io/killbasa/hive-web:latest
            ghcr.io/killbasa/hive-web:nightly
